ssh executor interface

diff --git a/executor_interfaces/sh_ssh_executor/sh_ssh_executor b/executor_interfaces/sh_ssh_executor/sh_ssh_executor
--- a/executor_interfaces/sh_ssh_executor/sh_ssh_executor
+++ b/executor_interfaces/sh_ssh_executor/sh_ssh_executor
@@ -27,11 +27,6 @@ LOG_LEVEL=DEBUG
 # Check for compatibility issues before start the server is also may produce
 # several aliases used by next includes (do not move this line)
 check_compatibility
-# EI Specific compatibility check
-EXPECT=$(which expect)
-[ "$EXPECT" = "" ] &&\
-  log ERROR "Executor interface $(basename $0), requires expect" &&\
-  exit 1
 
 # database functions
 . fgdb.sh
@@ -78,6 +73,32 @@ trap error_handler ERR
 #
 # Functions
 #
+
+# Execute the given command to remote host
+ssh() {
+  executor_interfaces/${target_executor}/${target_executor}/ssh_cmd\
+    "$infra_host"\
+    "$infra_port"\
+    "$infra_user"\
+    "$infra_password"\
+    "$infra_sshkey"\
+    "$@"
+  return $?
+}
+
+# Execute the given copy operation from/to remote host
+scp() {
+  executor_interfaces/${target_executor}/${target_executor}/scp_cmd\
+    "$infra_host"\
+    "$infra_port"\
+    "$infra_user"\
+    "$infra_password"\
+    "$infra_sshkey"\
+    "$1"\
+    "$2"\
+    "$3"
+  return $? 
+}
 
 #
 # SH SSH Executor Interface code
@@ -152,87 +173,64 @@ case $action in
   infra_host=$(cat $INFRA_PARAMS | grep ^host | awk -F'\t' '{ print $2 }')
   [ "$infra_host" = "" ] &&\
     log ERROR "Missing SSH host address for task: '"${task_id}"'" &&\
+    STATUS="ABORTED" &&\
     exit 1
+  infra_port=$(cat $INFRA_PARAMS | grep ^port | awk -F'\t' '{ print $2 }')
+  [ "$infra_port" = "" ] &&\
+    log WARN "Missing SSH port number for task: '"${task_id}"', assuming 22" &&\
+    infra_port=22
   infra_user=$(cat $INFRA_PARAMS | grep ^user | awk -F'\t' '{ print $2 }')
   [ "$infra_user" = "" ] &&\
     log ERROR "Missing SSH user name for task: '"${task_id}"'" &&\
+    STATUS="ABORTED" &&\
     exit 1
   infra_password=$(cat $INFRA_PARAMS | grep ^password | awk -F'\t' '{ print $2 }')
-  infra_sshkey=$(cat $INFRA_PARAMS | grep ^usesshkeyr | awk -F'\t' '{ print $2 }')
+  infra_sshkey=$(cat $INFRA_PARAMS | grep ^sshkey | awk -F'\t' '{ print $2 }')
   if  [ "$infra_password" = "" -a\
         "$infra_sshkey" = "" ]; then
-    [ "$infra_password" = "" ] &&\
-      log ERROR "Missing SSH password for task: '"${task_id}"'" &&\
-    [ "$infra_sshkey" = "" ] &&\
-      log ERROR "Missing SSH key for task: '"${task_id}"'" &&\
+    log ERROR "No SSH key or password specified for task: '"${task_id}"'" &&\
+    STATUS="ABORTED" &&\
     exit 1
   fi
   rm_temp INFRA_PARAMS
-  # Execute the requested job
-  cd $action_info_path
-  # Prepare the sandbox archive
-  get_temp IOSANDBOX
-  IOSANDBOX_FNAME=$(basename $IOSANDBOX)
-  tar cvfz $IOSANDBOX .
-  if [ "$infra_sshkey" = "" ]; then
-    log DEBUG "Starting SSH execution using keyfile path: '"$infra_sshkey"'"
-    # Create remote sandbox dir
-    REMOTE_IOSANDBOX=$(ssh -i $infra_sshkey $infra_user@$infra_host "mktemp")
-    # Transfer the sandbox
-    log DEBUG "Transger IOSANDBOX('"${IOSANDBOX}"->"${$REMOTE_IOSANDBOX/$IOSANDBOX_FNAME}"'"
-    scp -i $infra_sshkey $IOSANDBOX $infra_user@$infra_host:$REMOTE_IOSANDBOX/$IOSANDBOX_FNAME
-    # Create remote execution script
-    EXECUTOR_PID=$$
-    cat >sh_ssh_executor_script.sh <<EOF
-#!/bin/bash
-# Script automatically generated by sh_ssh_executor
-cd ${REMOTE_IOSANDBOX}
-tar xvfz ${IOSANDBOX_FNAME}
-$SHBE_EXECUTABLE $SHBE_ARGUMENTS 2>$SHBE_STDERR >$SHBE_STDOUT &
-SHBE_PID=$!
-echo "task_id=${SHBE_PID}" >> ${BARE_EXE_INFO}
-echo "executor_pid=${EXECUTOR_PID}" >> ${BARE_EXE_INFO}
-wait $SHBE_PID
-echo "end_ts="$(ts) >> $BARE_EXE_INFO
-SHBE_RET=$?
-echo "return_code=${SHBE_RET}" >> $BARE_EXE_INFO
-cd - >/dev/null
-EOF
-    # Transfer the sandbox
-    scp -i $infra_sshkey sh_ssh_executor_script.sh $infra_user@$infra_host:$REMOTE_IOSANDBOX/sh_ssh_executor_script.sh
-    # Execute the command
-    log DEBUG "Executing remote ssh command: \"$SHBE_EXECUTABLE $SHBE_ARGUMENTS 2>$SHBE_STDERR >$SHBE_STDOUT\""
-    ssh -i $infra_sshkey $infra_user@$infra_host "\
-      cd $REMOTE_IOSANDBOX &&\
-      chmod +x sh_ssh_executor_script.sh &&\
-      ./sh_ssh_executor_script.sh &"
-    # Retrieve the PID
-    status="RUNNING"
-    target_status="RUNNING"
-    update_queue_record $task_id || exit 1
-    # Wait execution completion
-    log DEBUG "Waiting for execution completion"
-    while true; do
-      scp -i $infra_user@$infra_host:$BARE_EXE_INFO $BARE_EXE_INFO
-      end_ts=$(cat $BARE_EXE_INFO | grep ^end_ts | awk -F'=' '{ print $2 }')
-      return_code=$(cat $BARE_EXE_INFO | grep ^return_code | awk -F'=' '{ print $2 }')
-      if [ "$end_ts" -ne 0 -a\
-           "$return_code" != "" ] &&\
-        break ||\
-        sleep 5
-    done
-    # Transfer
-    scp -rf $infra_user@$infra_host:$REMOTE_IOSANDBOX/ .
-    ssh -i $infra_sshkey $infra_user@$infra_host "rm -rf $REMOTE_IOSANDBOX"
-  else
-    # Transfer the sandbox
-    log DEBUG "Executing using password not yet implemented"
-    status="ABORTED"
-    target_status="ABORTED"
-    exit 1
-  fi
-  rm_temp IOSANDBOX
-  [ $return_code -eq 0 ] &&\
+
+  # Start SSH execution
+  tmp_dir=/tmp
+  action_info_name=$(basename $action_info_path)
+  action_info_dir=$(dirname $action_info_path)
+  remote_path=".ssh_executor/${action_info_name}"
+
+  # Prepare job files archive
+  cd $action_info_dir
+  tar cvfz ${tmp_dir}/${action_info_name}.tar.gz $action_info_name
+  cd - >/dev/null
+
+  # Send job archive to remote and extract
+  ssh "mkdir -p $remote_path"
+  scp "${tmp_dir}/${action_info_name}.tar.gz" ">" "${remote_path}/${action_info_name}.tar.gz"
+  ssh "cd .ssh_executor/${action_info_name} && tar xvfz ${action_info_name}.tar.gz -C . && rm ${action_info_name}.tar.gz"
+
+  # Job description
+  executable=$SHBE_EXECUTABLE
+  arguments="$SHBE_ARGUMENTS"
+  stdout=$SHBE_STDOUT
+  stderr=$SHBE_STDERR
+
+  # Execute command with ssh
+  ssh "cd ${remote_path}/${action_info_name} && ${executable} ${arguments} >${stdout} 2>${stderr}" &
+  SHBE_PID=$!
+  wait $SHBE_PID
+  SHBE_RET=$?
+
+  # Get and extract job file archive from remote, cleaning up unnecessary files
+  ssh "cd $remote_path && tar cvfz ${action_info_name}.tar.gz ${action_info_name}"
+  scp "${tmp_dir}/${action_info_name}.tar.gz" "<" "${remote_path}/${action_info_name}.tar.gz"
+  ssh "cd $remote_path && rm -f ${action_info_name}.tar.gz && rm -rf ${remote_path}/${action_info_name}"
+  tar xvfz "${tmp_dir}/${action_info_name}.tar.gz" -C $action_info_dir
+  rm -f "${tmp_dir}/${action_info_name}.tar.gz"
+
+  # Check execution
+  [ $SHBE_RET -eq 0 ] &&\
     status="DONE" &&\
     target_status="DONE" ||\
     (status="ABORTED" &&\
